<?xml version="1.0" encoding="utf-8"?><Database Name="aspnet-Bank-20210816074618" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDb)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\aspnet-Bank-20210816074618.mdf;Initial Catalog=aspnet-Bank-20210816074618;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DefaultConnection" Provider="System.Data.SqlClient" />
  <Function Name="dbo.spCrud" Method="spCrud">
    <Parameter Name="Id" Parameter="id" Type="System.Int32" DbType="Int" />
    <Parameter Name="Name" Parameter="name" Type="System.String" DbType="NVarChar(150)" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="NVarChar(150)" />
    <Parameter Name="Salary" Parameter="salary" Type="System.Int32" DbType="Int" />
    <Parameter Name="CrudOption" Parameter="crudOption" Type="System.String" DbType="NVarChar(150)" />
    <ElementType Name="spCrudResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Salary" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>